/**
 * AMARA OS — Seed Deals
 * Pre-scored, deal-gate-passed examples for dashboard development.
 * These represent what AMARA surfaces after all engines run.
 */

import { CanonicalDeal, emptyCloseStrategy } from "@/core/schema/canonical";

export const scoredDeals: CanonicalDeal[] = [
  {
    id: "deal_001",
    createdAt: new Date(Date.now() - 2 * 3600000).toISOString(),
    updatedAt: new Date(Date.now() - 2 * 3600000).toISOString(),
    lastScannedAt: new Date().toISOString(),
    sources: ["zillow", "propstream"],
    primarySource: "propstream",
    sourceConfidence: "HIGH",
    sourceIds: { zillow: "z_dfw_001", propstream: "ps_dfw_001", propelio: null, public_records: null, xleads: null, manual: null },
    sourceUrls: { zillow: null },
    address: "4821 Hickory Creek Dr",
    city: "Dallas",
    state: "TX",
    zip: "75228",
    county: "Dallas",
    apn: "00-1234-5678",
    lat: 32.7767,
    lng: -96.7970,
    market: "DFW",
    propertyType: "SFR",
    beds: 3,
    baths: 2,
    halfBaths: null,
    livingAreaSqft: 1480,
    lotSizeSqft: 7800,
    lotSizeAcres: 0.18,
    yearBuilt: 1965,
    stories: 1,
    garage: true,
    pool: false,
    basement: false,
    ownerName: "JOHNSON MARY T",
    ownerMailingAddress: "PO Box 11290, Garland TX 75041",
    ownerPhone: "214-555-0182",
    ownerEmail: null,
    ownershipYears: 22,
    lastSaleDate: "2001-08-22",
    lastSalePrice: 87000,
    estimatedEquity: 185000,
    estimatedEquityPct: 0.81,
    mortgageBalance: 43000,
    occupancyStatus: "TENANT_OCCUPIED",
    listingStatus: "ACTIVE",
    listPrice: 185000,
    originalListPrice: 219000,
    dom: 67,
    cdom: 67,
    listingDate: "2024-01-15",
    listingAgent: "John Smith",
    listingBrokerage: "HomeStar Realty",
    mls: "NTREIS",
    mlsId: "20558441",
    remarks: "Priced to sell! Investor special — as-is. Needs some TLC. Bring all offers. Tenant occupied, do not disturb tenant. Estate sale. Great investment opportunity.",
    priceHistory: [
      { date: "2024-01-15", price: 219000, event: "LISTED" },
      { date: "2024-02-20", price: 199000, event: "REDUCED" },
      { date: "2024-03-10", price: 185000, event: "REDUCED" },
    ],
    distress: {
      priceReduced: true,
      priceReductionCount: 2,
      priceReductionTotalPct: 0.155,
      domBucket: "60+",
      domDays: 67,
      distressKeywordsFound: ["as-is", "investor special", "TLC", "bring all offers", "tenant-occupied", "estate sale"],
      keywordDistressScore: 72,
      absenteeOwner: true,
      outOfStateOwner: false,
      corporateOwner: false,
      taxDelinquent: false,
      taxDelinquentAmountUSD: null,
      preforeclosure: false,
      foreclosure: false,
      auction: false,
      lis_pendens: false,
      probate: false,
      estate: true,
      inherited: false,
      codeViolation: false,
      permit_activity: false,
      vacancy: false,
      tenantOccupied: true,
      landlordFatigue: true,
      liens: false,
      lienCount: 0,
      openLienAmountUSD: null,
      totalDistressScore: 68,
    },
    valuation: {
      avm: 228000,
      avmSource: "propstream",
      avmConfidence: "MEDIUM",
      arvEstimate: 248000,
      arvLow: 235000,
      arvHigh: 262000,
      arvConfidence: "MEDIUM",
      arvCompsUsed: 5,
      asIsEstimate: 185000,
      asIsLow: 175000,
      asIsHigh: 195000,
      investorResaleEstimate: 168000,
      investorResaleLow: 155000,
      investorResaleHigh: 178000,
      rentEstimate: 1450,
      rentEstimateSource: "propstream",
      rehabEstimate: 35000,
      rehabLow: 28000,
      rehabHigh: 45000,
      rehabGrade: "COSMETIC",
      landDevelopmentValue: null,
      finishedLotValue: null,
      developmentRiskScore: null,
    },
    underwriting: {
      dealType: "WHOLESALE_ASSIGNMENT",
      exitStrategy: "ASSIGN_TO_FLIPPER",
      buyerResaleMax: 168000,
      assignmentFee: 10000,
      mao: 152400,
      projectedSpread: 15600,
      projectedProfit: 10000,
      flipProfit: null,
      flipROI: null,
      holdingCosts: null,
      closingCostsBuy: null,
      closingCostsSell: null,
      flipperMarginTarget: null,
      meetsMinimumFee: true,
      feeSurplus: 0,
      passesUnderwriting: true,
    },
    buyerLane: {
      buyerClass: "FLIPPER",
      exitConfidence: "HIGH",
      exitConfidenceScore: 82,
      matchedBuyerZIPs: ["75228", "75217", "75211"],
      matchedBuyerCount: 33,
      topBuyerProfileIds: [],
      estimatedDaysToAssign: 12,
      weeklyClosingPotential: true,
    },
    closeStrategy: {
      sellerPainProfile: "LANDLORD FATIGUE",
      likelyMotivation: "Absentee owner tired of managing tenant from a distance. 22 years of ownership means zero urgency to hold. Price reductions tell the whole story — she wants out.",
      negotiationAngle: "You are buying her headache. Don't frame it as a low offer — frame it as: 'You keep the tenant, the repairs, and the liability — OR you walk away with cash tomorrow.' Make the problem vivid, not the price.",
      openingApproach: "Don't open with price. Open with certainty: 'I'm a cash buyer. I close fast, no contingencies, no repairs required, and I'll handle the tenant situation. Can we talk today?'",
      anchorPriceLogic: "MAO is $152,400. Open at $148,000. Never go above $152,400. Move in $2,000 increments only if pressed. Each concession must extract a reciprocal commitment.",
      objectionResponse: "When she says 'that's too low': Don't apologize. Ask: 'What would it take for you to feel good about this?' Let her anchor down. Most sellers come down significantly when given the chance to talk.",
      followUpSchedule: "Day 0: Call today. Day 3: Follow-up if no response. Day 7: Written offer. Day 14: Final check-in. Don't let this go cold.",
      walkAwayTrigger: "Walk if she won't move to within $155,000 after two conversations. You have 37 markets. Protect your time.",
      coachingNote: "HIGH DISTRESS DEAL — Landlord fatigue + absentee + 67 DOM + 2 price cuts = motivated seller. Move on this TODAY.",
    },
    isQualifiedDeal: true,
    dealGateFailReasons: [],
    closeConfidence: "HIGH",
    closeConfidenceScore: 82,
    nextAction: "URGENT: Call seller within 4 hours — 67 DOM and 2 price cuts mean she's ready. Get this under contract.",
    nextActionDueDate: new Date(Date.now() + 4 * 3600000).toISOString(),
    accountabilityNote: "This deal has been in your queue for 2 hours. Don't let it go cold.",
    dealLabel: "WHOLESALE ASSIGNMENT — DFW — $15.6K SPREAD",
    urgencyFlag: "HOT",
  },
  {
    id: "deal_002",
    createdAt: new Date(Date.now() - 5 * 3600000).toISOString(),
    updatedAt: new Date(Date.now() - 5 * 3600000).toISOString(),
    lastScannedAt: new Date().toISOString(),
    sources: ["zillow"],
    primarySource: "zillow",
    sourceConfidence: "MEDIUM",
    sourceIds: { zillow: "z_phx_001", propstream: null, propelio: null, public_records: null, xleads: null, manual: null },
    sourceUrls: { zillow: null },
    address: "8843 W Sherman St",
    city: "Phoenix",
    state: "AZ",
    zip: "85031",
    county: "Maricopa",
    apn: "AZ-102-45-678",
    lat: 33.4484,
    lng: -112.0740,
    market: "Phoenix",
    propertyType: "SFR",
    beds: 3,
    baths: 2,
    halfBaths: null,
    livingAreaSqft: 1640,
    lotSizeSqft: 8500,
    lotSizeAcres: 0.20,
    yearBuilt: 1972,
    stories: 1,
    garage: true,
    pool: false,
    basement: false,
    ownerName: "GARCIA ESTATE — ROBERT GARCIA SR",
    ownerMailingAddress: "2210 N 44th St, Phoenix AZ 85008",
    ownerPhone: null,
    ownerEmail: null,
    ownershipYears: 31,
    lastSaleDate: "1993-04-11",
    lastSalePrice: 72000,
    estimatedEquity: 238000,
    estimatedEquityPct: 0.91,
    mortgageBalance: null,
    occupancyStatus: "VACANT",
    listingStatus: "ACTIVE",
    listPrice: 238000,
    originalListPrice: 279000,
    dom: 82,
    cdom: 82,
    listingDate: "2024-01-05",
    listingAgent: "Robert Chen",
    listingBrokerage: "Desert Investment Realty",
    mls: "ARMLS",
    mlsId: "AZ20558900",
    remarks: "Estate sale — sold as-is. Heirs selling. Property needs repairs and updating. Investor opportunity. Cash buyers only.",
    priceHistory: [
      { date: "2024-01-05", price: 279000, event: "LISTED" },
      { date: "2024-02-10", price: 259000, event: "REDUCED" },
      { date: "2024-03-05", price: 238000, event: "REDUCED" },
    ],
    distress: {
      priceReduced: true,
      priceReductionCount: 2,
      priceReductionTotalPct: 0.147,
      domBucket: "60+",
      domDays: 82,
      distressKeywordsFound: ["estate sale", "as-is", "heirs", "investor opportunity", "cash buyers"],
      keywordDistressScore: 76,
      absenteeOwner: false,
      outOfStateOwner: false,
      corporateOwner: false,
      taxDelinquent: false,
      taxDelinquentAmountUSD: null,
      preforeclosure: false,
      foreclosure: false,
      auction: false,
      lis_pendens: false,
      probate: true,
      estate: true,
      inherited: true,
      codeViolation: false,
      permit_activity: false,
      vacancy: true,
      tenantOccupied: false,
      landlordFatigue: false,
      liens: false,
      lienCount: 0,
      openLienAmountUSD: null,
      totalDistressScore: 74,
    },
    valuation: {
      avm: 285000,
      avmSource: "zillow_zestimate",
      avmConfidence: "MEDIUM",
      arvEstimate: 310000,
      arvLow: 295000,
      arvHigh: 328000,
      arvConfidence: "MEDIUM",
      arvCompsUsed: 6,
      asIsEstimate: 240000,
      asIsLow: 225000,
      asIsHigh: 255000,
      investorResaleEstimate: 218000,
      investorResaleLow: 205000,
      investorResaleHigh: 232000,
      rentEstimate: 1850,
      rentEstimateSource: "zillow_zestimate",
      rehabEstimate: 42000,
      rehabLow: 35000,
      rehabHigh: 52000,
      rehabGrade: "COSMETIC",
      landDevelopmentValue: null,
      finishedLotValue: null,
      developmentRiskScore: null,
    },
    underwriting: {
      dealType: "WHOLESALE_ASSIGNMENT",
      exitStrategy: "ASSIGN_TO_FLIPPER",
      buyerResaleMax: 218000,
      assignmentFee: 10000,
      mao: 198640,
      projectedSpread: 19360,
      projectedProfit: 10000,
      flipProfit: null,
      flipROI: null,
      holdingCosts: null,
      closingCostsBuy: null,
      closingCostsSell: null,
      flipperMarginTarget: null,
      meetsMinimumFee: true,
      feeSurplus: 0,
      passesUnderwriting: true,
    },
    buyerLane: {
      buyerClass: "FLIPPER",
      exitConfidence: "HIGH",
      exitConfidenceScore: 88,
      matchedBuyerZIPs: ["85031", "85040"],
      matchedBuyerCount: 27,
      topBuyerProfileIds: [],
      estimatedDaysToAssign: 11,
      weeklyClosingPotential: true,
    },
    closeStrategy: {
      sellerPainProfile: "ESTATE / INHERITED",
      likelyMotivation: "Heirs have held this 31 years of equity and just want it liquidated. Vacant property = carrying costs. Multiple decision-makers = frustration. Relief value is astronomical.",
      negotiationAngle: "Lead with empathy. Acknowledge the process is difficult. Position yourself as the easiest exit — no showings, no repairs, no waiting. The value you offer isn't the price, it's the peace.",
      openingApproach: "Acknowledge the loss. Say: 'I understand there may be multiple people involved. My offer is simple — as-is, cash, you pick the close date. I make it easy.'",
      anchorPriceLogic: "MAO is $198,640. Open at $192,000. Never go above $198,640. The heirs are not emotionally attached to price — they're attached to resolution.",
      objectionResponse: "When they push back: 'I understand. The market for cash-as-is buyers has spoken — this is what the math supports. I can close in 10 days and end this process for everyone.'",
      followUpSchedule: "Day 0: Call attorney/heir contact today. Day 3: Follow-up. Day 7: Written offer. Day 14: Final check. Estate deals take patience — stay in the rotation.",
      walkAwayTrigger: "Walk if they won't move to within $205,000 after two conversations. Estate sellers eventually capitulate — or they don't. Don't chase.",
      coachingNote: "HIGH DISTRESS — Estate + vacant + 82 DOM + 2 price cuts. Heirs want this GONE. Lead with speed and certainty, not price.",
    },
    isQualifiedDeal: true,
    dealGateFailReasons: [],
    closeConfidence: "HIGH",
    closeConfidenceScore: 88,
    nextAction: "Call listing agent TODAY. Confirm heir contact info. Present cash offer at $192,000. This is a clean close — move fast.",
    nextActionDueDate: new Date(Date.now() + 6 * 3600000).toISOString(),
    accountabilityNote: "Estate deals with vacant properties move fast once heirs align. Don't wait.",
    dealLabel: "WHOLESALE ASSIGNMENT — PHOENIX — $19.4K SPREAD",
    urgencyFlag: "HOT",
  },
  {
    id: "deal_003",
    createdAt: new Date(Date.now() - 12 * 3600000).toISOString(),
    updatedAt: new Date(Date.now() - 12 * 3600000).toISOString(),
    lastScannedAt: new Date().toISOString(),
    sources: ["zillow"],
    primarySource: "zillow",
    sourceConfidence: "MEDIUM",
    sourceIds: { zillow: "z_dfw_002", propstream: null, propelio: null, public_records: null, xleads: null, manual: null },
    sourceUrls: { zillow: null },
    address: "2211 Morrell Ave",
    city: "Fort Worth",
    state: "TX",
    zip: "76104",
    county: "Tarrant",
    apn: "TX-076-22-411",
    lat: 32.7204,
    lng: -97.3208,
    market: "DFW",
    propertyType: "SFR",
    beds: 3,
    baths: 1,
    halfBaths: null,
    livingAreaSqft: 1220,
    lotSizeSqft: 6200,
    lotSizeAcres: 0.14,
    yearBuilt: 1958,
    stories: 1,
    garage: false,
    pool: false,
    basement: false,
    ownerName: "HENDERSON PROPERTIES LLC",
    ownerMailingAddress: "5500 Addison Circle, Addison TX 75001",
    ownerPhone: null,
    ownerEmail: null,
    ownershipYears: 8,
    lastSaleDate: "2016-03-15",
    lastSalePrice: 68000,
    estimatedEquity: 110000,
    estimatedEquityPct: 0.73,
    mortgageBalance: 32000,
    occupancyStatus: "VACANT",
    listingStatus: "ACTIVE",
    listPrice: 142000,
    originalListPrice: 165000,
    dom: 91,
    cdom: 91,
    listingDate: "2023-12-01",
    listingAgent: "Maria Garcia",
    listingBrokerage: "Lone Star Investments",
    mls: "NTREIS",
    mlsId: "20541872",
    remarks: "Fixer-upper opportunity. Motivated seller. Vacant. Cash buyers preferred. Needs full interior update. ARV estimated $190K.",
    priceHistory: [
      { date: "2023-12-01", price: 165000, event: "LISTED" },
      { date: "2024-01-15", price: 155000, event: "REDUCED" },
      { date: "2024-02-28", price: 142000, event: "REDUCED" },
    ],
    distress: {
      priceReduced: true,
      priceReductionCount: 2,
      priceReductionTotalPct: 0.139,
      domBucket: "90+",
      domDays: 91,
      distressKeywordsFound: ["fixer-upper", "motivated seller", "vacant", "cash buyers", "needs work"],
      keywordDistressScore: 65,
      absenteeOwner: true,
      outOfStateOwner: false,
      corporateOwner: true,
      taxDelinquent: false,
      taxDelinquentAmountUSD: null,
      preforeclosure: false,
      foreclosure: false,
      auction: false,
      lis_pendens: false,
      probate: false,
      estate: false,
      inherited: false,
      codeViolation: false,
      permit_activity: false,
      vacancy: true,
      tenantOccupied: false,
      landlordFatigue: true,
      liens: false,
      lienCount: 0,
      openLienAmountUSD: null,
      totalDistressScore: 62,
    },
    valuation: {
      avm: 178000,
      avmSource: "zillow_zestimate",
      avmConfidence: "MEDIUM",
      arvEstimate: 192000,
      arvLow: 182000,
      arvHigh: 204000,
      arvConfidence: "MEDIUM",
      arvCompsUsed: 4,
      asIsEstimate: 145000,
      asIsLow: 135000,
      asIsHigh: 155000,
      investorResaleEstimate: 132000,
      investorResaleLow: 122000,
      investorResaleHigh: 142000,
      rentEstimate: 1200,
      rentEstimateSource: "zillow_zestimate",
      rehabEstimate: 28000,
      rehabLow: 22000,
      rehabHigh: 36000,
      rehabGrade: "COSMETIC",
      landDevelopmentValue: null,
      finishedLotValue: null,
      developmentRiskScore: null,
    },
    underwriting: {
      dealType: "WHOLESALE_ASSIGNMENT",
      exitStrategy: "ASSIGN_TO_FLIPPER",
      buyerResaleMax: 132000,
      assignmentFee: 10000,
      mao: 118960,
      projectedSpread: 13040,
      projectedProfit: 10000,
      flipProfit: null,
      flipROI: null,
      holdingCosts: null,
      closingCostsBuy: null,
      closingCostsSell: null,
      flipperMarginTarget: null,
      meetsMinimumFee: true,
      feeSurplus: 0,
      passesUnderwriting: true,
    },
    buyerLane: {
      buyerClass: "FLIPPER",
      exitConfidence: "HIGH",
      exitConfidenceScore: 79,
      matchedBuyerZIPs: ["76104", "76105"],
      matchedBuyerCount: 14,
      topBuyerProfileIds: [],
      estimatedDaysToAssign: 15,
      weeklyClosingPotential: true,
    },
    closeStrategy: {
      sellerPainProfile: "LANDLORD FATIGUE",
      likelyMotivation: "Corporate LLC owner — this is a numbers decision, not emotional. They're holding a vacant property bleeding cash. At 91 DOM and 2 cuts, the LLC wants to redeploy that capital.",
      negotiationAngle: "Speak the LLC language: ROI, carrying costs, opportunity cost. Say: 'Every month this sits vacant, you're losing $800+ in holding. A clean close now stops the bleeding.'",
      openingApproach: "Skip the emotion. Lead with math: 'I run a quick-close operation. All cash, no contingencies, 10-day close. What's the number that gets this off your books?'",
      anchorPriceLogic: "MAO is $118,960. Open at $112,000. LLC sellers respond to rational offers — don't anchor too far below or they won't engage.",
      objectionResponse: "LLC pushes back: 'What's your analysis?' Give them the math. Show them what a cash close is worth versus carrying another 60 days.",
      followUpSchedule: "Day 0: Call or email today. Day 2: Follow-up. Day 5: Written offer. Day 10: Final. LLCs respond faster than individuals.",
      walkAwayTrigger: "Walk if they won't move below $125,000. The number doesn't work above that.",
      coachingNote: "CORPORATE SELLER at 91 DOM — speak math, not emotion. They want certainty and speed. Deliver both.",
    },
    isQualifiedDeal: true,
    dealGateFailReasons: [],
    closeConfidence: "HIGH",
    closeConfidenceScore: 79,
    nextAction: "Call LLC contact within 24 hours. Present offer at $112,000 cash, 10-day close. Have contract ready.",
    nextActionDueDate: new Date(Date.now() + 24 * 3600000).toISOString(),
    accountabilityNote: "91 DOM — this deal is aging. Move today.",
    dealLabel: "WHOLESALE ASSIGNMENT — DFW — $13K SPREAD",
    urgencyFlag: "WARM",
  },
];
