/**
 * Seed script: 10 realistic Las Vegas / Henderson NV land parcels
 *
 * Usage:
 *   DATABASE_URL=postgresql://... npx tsx scripts/seed-vegas.ts
 *
 * Or via docker:
 *   docker-compose exec backend npx tsx scripts/seed-vegas.ts
 */
import "dotenv/config";
import { db } from "../src/db/client";
import { landParcels } from "../src/db/schema";
import { computeFeasibilityScore, parcelRowToScoreInput } from "../src/services/feasibility";
import type { NewLandParcel } from "../src/db/schema";

const rawParcels: Omit<NewLandParcel, "feasibilityScore" | "recommendation">[] = [
  {
    apn: "138-24-810-001",
    addressLine1: "4820 E Sunset Rd",
    city: "Henderson",
    state: "NV",
    zip: "89014",
    county: "Clark",
    jurisdiction: "Henderson",
    latitude: 36.0331,
    longitude: -115.0768,
    areaSqft: 43560,
    areaAcres: 1.0,
    ownerName: "DESERT LAND TRUST LLC",
    yearsOwned: "14.5",
    lastSaleDate: "2010-03-12",
    lastSalePrice: "185000",
    assessedLandValue: "210000",
    assessedTotalValue: "210000",
    zoningCode: "R-1",
    zoningDescription: "Single Family Residential",
    allowedUseCategory: "Residential",
    minLotSizeSqft: 6000,
    maxUnitsPerAcre: 7,
    estMaxLotCount: 7,
    estMaxUnitCount: 7,
    topographyClass: "FLAT",
    floodZoneCode: "X",
    hasExistingStructure: false,
    isVacantLand: true,
    hasWater: true,
    hasSewer: true,
    hasPower: true,
    hasGas: true,
    isTaxDelinquent: true,
    taxDelinquentAmount: "18200",
    hasCodeViolations: false,
    nearbyNewBuildPricePerUnit: "480000",
    estimatedLandValuePerPotentialLot: "42000",
    estimatedLandValueTotal: "294000",
    estimatedLandValuePerAcre: "294000",
    targetProductType: "SFR Infill",
    pipelineStatus: "NEW",
  },
  {
    apn: "176-09-201-014",
    addressLine1: "7200 W Cheyenne Ave",
    city: "Las Vegas",
    state: "NV",
    zip: "89129",
    county: "Clark",
    jurisdiction: "Clark County",
    latitude: 36.2195,
    longitude: -115.2598,
    areaSqft: 217800,
    areaAcres: 5.0,
    ownerName: "CHEYENNE PROPERTIES LLC",
    yearsOwned: "22.0",
    lastSaleDate: "2002-08-04",
    lastSalePrice: "520000",
    assessedLandValue: "890000",
    assessedTotalValue: "890000",
    zoningCode: "R-2",
    zoningDescription: "Medium Density Residential",
    allowedUseCategory: "Multifamily",
    minLotSizeSqft: 4000,
    maxUnitsPerAcre: 18,
    estMaxLotCount: 25,
    estMaxUnitCount: 90,
    topographyClass: "FLAT",
    floodZoneCode: "X",
    hasExistingStructure: false,
    isVacantLand: true,
    hasWater: true,
    hasSewer: true,
    hasPower: true,
    hasGas: true,
    isTaxDelinquent: false,
    hasCodeViolations: false,
    hasPreforeclosureFlag: true,
    nearbyNewBuildPricePerUnit: "350000",
    estimatedLandValuePerPotentialLot: "32000",
    estimatedLandValueTotal: "800000",
    estimatedLandValuePerAcre: "160000",
    targetProductType: "Townhomes / BTR",
    pipelineStatus: "NEW",
  },
  {
    apn: "162-33-101-002",
    addressLine1: "3950 S Hualapai Way",
    city: "Las Vegas",
    state: "NV",
    zip: "89147",
    county: "Clark",
    jurisdiction: "Las Vegas",
    latitude: 36.1012,
    longitude: -115.3088,
    areaSqft: 87120,
    areaAcres: 2.0,
    ownerName: "JAMES R KOWALSKI",
    yearsOwned: "31.0",
    lastSaleDate: "1993-05-18",
    lastSalePrice: "95000",
    assessedLandValue: "420000",
    assessedTotalValue: "420000",
    zoningCode: "C-1",
    zoningDescription: "Local Business",
    allowedUseCategory: "Mixed Use",
    maxUnitsPerAcre: 20,
    estMaxLotCount: 12,
    estMaxUnitCount: 40,
    topographyClass: "FLAT",
    floodZoneCode: "X",
    hasExistingStructure: true,
    existingUseType: "Vacant Commercial",
    isVacantStructure: true,
    hasWater: true,
    hasSewer: true,
    hasPower: true,
    hasGas: true,
    isTaxDelinquent: true,
    taxDelinquentAmount: "44100",
    hasCodeViolations: true,
    codeViolationCount: 3,
    nearbyNewBuildPricePerUnit: "410000",
    estimatedLandValuePerPotentialLot: "35000",
    estimatedLandValueTotal: "420000",
    estimatedLandValuePerAcre: "210000",
    targetProductType: "Mixed Use / Live-Work",
    pipelineStatus: "NEW",
  },
  {
    apn: "125-18-401-007",
    addressLine1: "1840 N Decatur Blvd",
    city: "Las Vegas",
    state: "NV",
    zip: "89108",
    county: "Clark",
    jurisdiction: "Las Vegas",
    latitude: 36.2001,
    longitude: -115.1847,
    areaSqft: 130680,
    areaAcres: 3.0,
    ownerName: "NEVADA LAND GROUP INC",
    yearsOwned: "8.5",
    lastSaleDate: "2015-11-30",
    lastSalePrice: "610000",
    assessedLandValue: "595000",
    assessedTotalValue: "595000",
    zoningCode: "R-CL",
    zoningDescription: "Single Family Compact Lot",
    allowedUseCategory: "Residential",
    minLotSizeSqft: 3500,
    maxUnitsPerAcre: 12,
    estMaxLotCount: 15,
    estMaxUnitCount: 15,
    topographyClass: "FLAT",
    floodZoneCode: "AE",
    hasEnvironmentalFlag: false,
    hasExistingStructure: false,
    isVacantLand: true,
    hasWater: true,
    hasSewer: true,
    hasPower: true,
    hasGas: true,
    isTaxDelinquent: false,
    hasCodeViolations: false,
    nearbyNewBuildPricePerUnit: "430000",
    estimatedLandValuePerPotentialLot: "39000",
    estimatedLandValueTotal: "585000",
    estimatedLandValuePerAcre: "195000",
    targetProductType: "Detached SFR",
    pipelineStatus: "NEW",
  },
  {
    apn: "191-27-602-019",
    addressLine1: "9600 S Eastern Ave",
    city: "Henderson",
    state: "NV",
    zip: "89002",
    county: "Clark",
    jurisdiction: "Henderson",
    latitude: 35.9714,
    longitude: -115.0993,
    areaSqft: 391040,
    areaAcres: 8.98,
    ownerName: "EASTERN CORRIDOR HOLDINGS LLC",
    yearsOwned: "11.2",
    lastSaleDate: "2013-02-14",
    lastSalePrice: "1200000",
    assessedLandValue: "1850000",
    assessedTotalValue: "1850000",
    zoningCode: "R-2",
    zoningDescription: "Medium Density Residential",
    allowedUseCategory: "Residential",
    minLotSizeSqft: 4000,
    maxUnitsPerAcre: 15,
    estMaxLotCount: 38,
    estMaxUnitCount: 134,
    topographyClass: "FLAT",
    floodZoneCode: "X",
    hasExistingStructure: false,
    isVacantLand: true,
    hasWater: true,
    hasSewer: true,
    hasPower: true,
    hasGas: true,
    isTaxDelinquent: false,
    hasCodeViolations: false,
    nearbyNewBuildPricePerUnit: "385000",
    estimatedLandValuePerPotentialLot: "48000",
    estimatedLandValueTotal: "1824000",
    estimatedLandValuePerAcre: "203000",
    targetProductType: "Townhome / BTR",
    pipelineStatus: "NEW",
  },
  {
    apn: "140-08-210-003",
    addressLine1: "2255 E Warm Springs Rd",
    city: "Las Vegas",
    state: "NV",
    zip: "89119",
    county: "Clark",
    jurisdiction: "Las Vegas",
    latitude: 36.0598,
    longitude: -115.0924,
    areaSqft: 65340,
    areaAcres: 1.5,
    ownerName: "SUNSHINE REALTY TRUST",
    yearsOwned: "18.0",
    lastSaleDate: "2006-07-22",
    lastSalePrice: "380000",
    assessedLandValue: "540000",
    assessedTotalValue: "540000",
    zoningCode: "R-MH",
    zoningDescription: "Mobile Home",
    allowedUseCategory: "Residential",
    minLotSizeSqft: 3200,
    maxUnitsPerAcre: 10,
    estMaxLotCount: 8,
    estMaxUnitCount: 15,
    topographyClass: "FLAT",
    floodZoneCode: "X",
    hasExistingStructure: true,
    existingUseType: "Abandoned Mobile Home Park",
    isVacantStructure: true,
    hasWater: true,
    hasSewer: true,
    hasPower: true,
    hasGas: false,
    isTaxDelinquent: true,
    taxDelinquentAmount: "29300",
    hasCodeViolations: true,
    codeViolationCount: 7,
    hasPreforeclosureFlag: true,
    nearbyNewBuildPricePerUnit: "395000",
    estimatedLandValuePerPotentialLot: "41000",
    estimatedLandValueTotal: "328000",
    estimatedLandValuePerAcre: "219000",
    targetProductType: "SFR Infill / ADU",
    pipelineStatus: "NEW",
  },
  {
    apn: "177-15-301-021",
    addressLine1: "5500 W Craig Rd",
    city: "North Las Vegas",
    state: "NV",
    zip: "89031",
    county: "Clark",
    jurisdiction: "North Las Vegas",
    latitude: 36.2659,
    longitude: -115.2348,
    areaSqft: 261360,
    areaAcres: 6.0,
    ownerName: "CRAIG DEVELOPMENT GROUP",
    yearsOwned: "5.5",
    lastSaleDate: "2018-09-03",
    lastSalePrice: "780000",
    assessedLandValue: "920000",
    assessedTotalValue: "920000",
    zoningCode: "R-1",
    zoningDescription: "Single Family Residential",
    allowedUseCategory: "Residential",
    minLotSizeSqft: 6000,
    maxUnitsPerAcre: 7,
    estMaxLotCount: 28,
    estMaxUnitCount: 28,
    topographyClass: "FLAT",
    floodZoneCode: "X",
    hasExistingStructure: false,
    isVacantLand: true,
    hasWater: true,
    hasSewer: true,
    hasPower: true,
    hasGas: true,
    isTaxDelinquent: false,
    hasCodeViolations: false,
    nearbyNewBuildPricePerUnit: "445000",
    estimatedLandValuePerPotentialLot: "33000",
    estimatedLandValueTotal: "924000",
    estimatedLandValuePerAcre: "154000",
    targetProductType: "SFR Subdivision",
    pipelineStatus: "NEW",
  },
  {
    apn: "163-01-501-008",
    addressLine1: "8800 W Tropicana Ave",
    city: "Las Vegas",
    state: "NV",
    zip: "89147",
    county: "Clark",
    jurisdiction: "Las Vegas",
    latitude: 36.0792,
    longitude: -115.3147,
    areaSqft: 174240,
    areaAcres: 4.0,
    ownerName: "TROPICANA WEST VENTURES",
    yearsOwned: "27.0",
    lastSaleDate: "1997-04-10",
    lastSalePrice: "240000",
    assessedLandValue: "1100000",
    assessedTotalValue: "1100000",
    zoningCode: "PD",
    zoningDescription: "Planned Development",
    allowedUseCategory: "Mixed Use",
    maxUnitsPerAcre: 22,
    estMaxLotCount: 30,
    estMaxUnitCount: 88,
    topographyClass: "FLAT",
    floodZoneCode: "X",
    hasExistingStructure: false,
    isVacantLand: true,
    hasWater: true,
    hasSewer: true,
    hasPower: true,
    hasGas: true,
    isTaxDelinquent: false,
    hasCodeViolations: false,
    nearbyNewBuildPricePerUnit: "520000",
    estimatedLandValuePerPotentialLot: "37000",
    estimatedLandValueTotal: "1110000",
    estimatedLandValuePerAcre: "277500",
    targetProductType: "Condos / Mixed Use",
    pipelineStatus: "NEW",
  },
  {
    apn: "124-29-407-016",
    addressLine1: "3310 N Rainbow Blvd",
    city: "Las Vegas",
    state: "NV",
    zip: "89108",
    county: "Clark",
    jurisdiction: "Las Vegas",
    latitude: 36.2148,
    longitude: -115.2411,
    areaSqft: 108900,
    areaAcres: 2.5,
    ownerName: "RAINBOW LAND CORP",
    yearsOwned: "3.0",
    lastSaleDate: "2021-06-01",
    lastSalePrice: "650000",
    assessedLandValue: "625000",
    assessedTotalValue: "625000",
    zoningCode: "R-2",
    zoningDescription: "Medium Density Residential",
    allowedUseCategory: "Residential",
    minLotSizeSqft: 4000,
    maxUnitsPerAcre: 15,
    estMaxLotCount: 14,
    estMaxUnitCount: 37,
    topographyClass: "ROLLING",
    floodZoneCode: "X",
    hasExistingStructure: false,
    isVacantLand: true,
    hasWater: true,
    hasSewer: false,
    hasPower: true,
    hasGas: true,
    isTaxDelinquent: false,
    hasCodeViolations: false,
    nearbyNewBuildPricePerUnit: "415000",
    estimatedLandValuePerPotentialLot: "44000",
    estimatedLandValueTotal: "616000",
    estimatedLandValuePerAcre: "246400",
    targetProductType: "Townhomes",
    pipelineStatus: "NEW",
  },
  {
    apn: "165-31-202-005",
    addressLine1: "6700 S Durango Dr",
    city: "Las Vegas",
    state: "NV",
    zip: "89113",
    county: "Clark",
    jurisdiction: "Las Vegas",
    latitude: 36.0489,
    longitude: -115.3012,
    areaSqft: 348480,
    areaAcres: 8.0,
    ownerName: "DURANGO MASTER TRUST",
    yearsOwned: "16.5",
    lastSaleDate: "2007-11-08",
    lastSalePrice: "2100000",
    assessedLandValue: "3200000",
    assessedTotalValue: "3200000",
    zoningCode: "R-1",
    zoningDescription: "Single Family Residential",
    allowedUseCategory: "Residential",
    minLotSizeSqft: 6000,
    maxUnitsPerAcre: 7,
    estMaxLotCount: 40,
    estMaxUnitCount: 40,
    topographyClass: "FLAT",
    floodZoneCode: "X",
    hasExistingStructure: false,
    isVacantLand: true,
    hasWater: true,
    hasSewer: true,
    hasPower: true,
    hasGas: true,
    isTaxDelinquent: false,
    hasCodeViolations: false,
    nearbyNewBuildPricePerUnit: "575000",
    estimatedLandValuePerPotentialLot: "80000",
    estimatedLandValueTotal: "3200000",
    estimatedLandValuePerAcre: "400000",
    targetProductType: "Premium SFR",
    pipelineStatus: "NEW",
  },
];

async function seed() {
  console.log("Seeding 10 Las Vegas parcels…");

  for (const raw of rawParcels) {
    const scoreInput = parcelRowToScoreInput({
      areaAcres: raw.areaAcres ?? null,
      estMaxLotCount: raw.estMaxLotCount ?? null,
      zoningCode: raw.zoningCode ?? null,
      allowedUseCategory: raw.allowedUseCategory ?? null,
      isTaxDelinquent: raw.isTaxDelinquent ?? null,
      hasCodeViolations: raw.hasCodeViolations ?? null,
      yearsOwned: raw.yearsOwned ?? null,
      floodZoneCode: raw.floodZoneCode ?? null,
      topographyClass: raw.topographyClass ?? null,
      estimatedLandValuePerPotentialLot: raw.estimatedLandValuePerPotentialLot ?? null,
      nearbyNewBuildPricePerUnit: raw.nearbyNewBuildPricePerUnit ?? null,
    });
    const { score, recommendation } = computeFeasibilityScore(scoreInput);

    const [inserted] = await db
      .insert(landParcels)
      .values({ ...raw, feasibilityScore: score, recommendation })
      .returning({ id: landParcels.id, apn: landParcels.apn, feasibilityScore: landParcels.feasibilityScore, recommendation: landParcels.recommendation });

    console.log(`  ✓ ${inserted.apn} — score: ${inserted.feasibilityScore} → ${inserted.recommendation}`);
  }

  console.log("\nDone. Seeded 10 Vegas parcels.");
  process.exit(0);
}

seed().catch((err) => {
  console.error("Seed failed:", err);
  process.exit(1);
});
