import {
  AlignmentType,
  Document,
  HeadingLevel,
  Packer,
  Paragraph,
  Table,
  TableCell,
  TableRow,
  TextRun,
  WidthType,
} from 'docx';
import type { CurativeItemRow, InstrumentRow, Project } from '../types/index.js';

function headerCell(text: string): TableCell {
  return new TableCell({
    width: { size: 100 / 7, type: WidthType.PERCENTAGE },
    children: [new Paragraph({ children: [new TextRun({ text, bold: true })] })],
  });
}

function cell(text: string): TableCell {
  return new TableCell({
    width: { size: 100 / 7, type: WidthType.PERCENTAGE },
    children: [new Paragraph(text)],
  });
}

function instrumentsTable(instruments: Array<InstrumentRow & { sequence_no: number }>): Table {
  const header = new TableRow({
    tableHeader: true,
    children: [
      headerCell('#'),
      headerCell('Recording Date'),
      headerCell('Instrument Type'),
      headerCell('Grantor'),
      headerCell('Grantee'),
      headerCell('Vol/Page or Doc #'),
      headerCell('Legal Description'),
    ],
  });

  const rows = instruments.map(
    (row) =>
      new TableRow({
        children: [
          cell(String(row.sequence_no)),
          cell(row.recording_date ?? '—'),
          cell(row.instrument_type ?? '—'),
          cell(row.grantors.join('; ') || '—'),
          cell(row.grantees.join('; ') || '—'),
          cell(
            row.instrument_number
              ? `#${row.instrument_number}`
              : row.volume && row.page
                ? `Vol. ${row.volume} / Pg. ${row.page}`
                : '—',
          ),
          cell(row.legal_description ?? '—'),
        ],
      }),
  );

  return new Table({ width: { size: 100, type: WidthType.PERCENTAGE }, rows: [header, ...rows] });
}

function curativeSection(items: CurativeItemRow[]): Paragraph[] {
  if (items.length === 0) {
    return [new Paragraph({ text: 'No curative items were flagged by automated review.' })];
  }

  const bySeverity = { critical: 0, warning: 0, info: 0 };
  for (const item of items) bySeverity[item.severity]++;

  const paragraphs: Paragraph[] = [
    new Paragraph({
      text: `${bySeverity.critical} critical, ${bySeverity.warning} warning, ${bySeverity.info} informational item(s).`,
    }),
  ];

  for (const item of items) {
    paragraphs.push(
      new Paragraph({
        bullet: { level: 0 },
        children: [
          new TextRun({ text: `[${item.severity.toUpperCase()}] `, bold: true }),
          new TextRun({ text: `${item.category}: ${item.description}` }),
        ],
      }),
    );
  }

  return paragraphs;
}

export async function buildTitleReportDocx(
  project: Project,
  instruments: Array<InstrumentRow & { sequence_no: number }>,
  curativeItems: CurativeItemRow[],
): Promise<Buffer> {
  const tract = [
    project.survey_section ? `Section ${project.survey_section}` : null,
    project.survey_block ? `Block ${project.survey_block}` : null,
    project.survey_township,
  ]
    .filter(Boolean)
    .join(', ');

  const doc = new Document({
    sections: [
      {
        children: [
          new Paragraph({
            heading: HeadingLevel.TITLE,
            alignment: AlignmentType.CENTER,
            text: 'Mineral Title Runsheet Report',
          }),
          new Paragraph({
            alignment: AlignmentType.CENTER,
            text: project.name,
          }),
          new Paragraph({
            alignment: AlignmentType.CENTER,
            children: [
              new TextRun({
                text: `${tract || 'Tract not specified'} — ${project.county} County, ${project.state}`,
                italics: true,
              }),
            ],
          }),
          new Paragraph({ text: '' }),

          new Paragraph({ heading: HeadingLevel.HEADING_1, text: 'Chain of Title' }),
          instrumentsTable(instruments),
          new Paragraph({ text: '' }),

          new Paragraph({ heading: HeadingLevel.HEADING_1, text: 'Curative Items' }),
          ...curativeSection(curativeItems),
          new Paragraph({ text: '' }),

          new Paragraph({
            heading: HeadingLevel.HEADING_2,
            text: 'Notes',
          }),
          new Paragraph({
            text:
              'This report was generated by an automated abstracting pipeline (heuristic field extraction, ' +
              'not attorney review). Confirm all extracted fields and curative findings against the underlying ' +
              'recorded instruments before relying on this runsheet for a title opinion or acquisition decision.',
          }),
        ],
      },
    ],
  });

  return Packer.toBuffer(doc);
}
