"""
Manual chain-of-title seed for parcel 11-409-19.
Source: Harrison County IDX — BK 1441 PG 1269 and back-chain references.
Instruments ordered oldest → newest.
"""

INSTRUMENTS = [
    {
        "seq": 1,
        "type": "DEED",
        "grantor": "DAVISSON",
        "grantee": "MONROE",
        "book": "57",
        "page": "238",
        "date_recorded": "1874",
        "date_instr": "1874",
        "description": "51 acres — per chain reference in BK 1441/1269",
        "acres": "51",
        "interest": "",
        "consideration": "",
        "doc_url": "",
        "notes": "Earliest in chain; referenced in 1903 Shuttleworth deed",
    },
    {
        "seq": 2,
        "type": "DEED",
        "grantor": "SHUTTLEWORTH",
        "grantee": "MONROE",
        "book": "61",
        "page": "434",
        "date_recorded": "1879",
        "date_instr": "1879",
        "description": "Per chain reference in BK 1441/1269",
        "acres": "",
        "interest": "",
        "consideration": "",
        "doc_url": "",
        "notes": "",
    },
    {
        "seq": 3,
        "type": "DEED",
        "grantor": "BUMGARDNER",
        "grantee": "MONROE",
        "book": "68",
        "page": "329",
        "date_recorded": "1884",
        "date_instr": "1884",
        "description": "60 acres — per chain reference in BK 1441/1269",
        "acres": "60",
        "interest": "",
        "consideration": "",
        "doc_url": "",
        "notes": "",
    },
    {
        "seq": 4,
        "type": "DEED",
        "grantor": "BUMGARDNER",
        "grantee": "MONROE",
        "book": "75",
        "page": "97",
        "date_recorded": "1888",
        "date_instr": "1888",
        "description": "10 acres — per chain reference in BK 1441/1269",
        "acres": "10",
        "interest": "",
        "consideration": "",
        "doc_url": "",
        "notes": "",
    },
    {
        "seq": 5,
        "type": "DEED",
        "grantor": "THOMPSON, COMMISSIONER",
        "grantee": "SHUTTLEWORTH",
        "book": "109",
        "page": "403",
        "date_recorded": "1899",
        "date_instr": "1899",
        "description": "Commissioner deed to Shuttleworth — per chain reference in BK 1441/1269",
        "acres": "",
        "interest": "",
        "consideration": "",
        "doc_url": "",
        "notes": "",
    },
    {
        "seq": 6,
        "type": "DEED",
        "grantor": "SHUTTLEWORTH",
        "grantee": "STEWART",
        "book": "136",
        "page": "259",
        "date_recorded": "1903",
        "date_instr": "1903",
        "description": "121.5 acres — RESERVED 1/2 MINERALS — Elk-Outside District",
        "acres": "121.5",
        "interest": "Surface + 1/2 minerals conveyed; 1/2 minerals RESERVED by grantor",
        "consideration": "",
        "doc_url": "",
        "notes": "KEY INSTRUMENT: 1/2 mineral reservation creates split estate. "
                 "Antero WV mineral reservation analysis applies.",
    },
    {
        "seq": 7,
        "type": "FIDUCIARY",
        "grantor": "SHUTTLEWORTH ESTATE",
        "grantee": "SHUTTLEWORTH HEIRS",
        "book": "FID 10",
        "page": "247",
        "date_recorded": "1919",
        "date_instr": "1919",
        "description": "Estate settlement — heirs: Lillie A., Helen, Lorene, Mary, Samuel, Betty Jane Shuttleworth",
        "acres": "",
        "interest": "Reserved mineral interest distributed to heirs",
        "consideration": "",
        "doc_url": "",
        "notes": "Heirs hold the reserved 1/2 mineral interest from DB 136/259. "
                 "Remaining 5/6 of 1/6 (= 5/6 undivided) needs Shuttleworth heirs research.",
    },
    {
        "seq": 8,
        "type": "DEED",
        "grantor": "A. DEAN BURNS, EXECUTOR ESTATE OF HELEN S. KRAMER",
        "grantee": "MASTER MINERAL HOLDINGS INC., TEXAS CORPORATION",
        "book": "1441",
        "page": "1269",
        "date_recorded": "2010-02-10",
        "date_instr": "2010-01-19",
        "description": (
            "Undivided 1/6 interest in oil, gas, and coalbed methane. "
            "Elk-Outside District, Harrison County WV. "
            "Parcels: 17-11-0409-0019-0000 through -0003. "
            "Tax assessment: Shuttleworth Maynard Heirs .50 INT 121.072 AC O&G Gnatty Creek. "
            "Surface owner: Burns family, Knoll View Road, Mount Clare WV 26408."
        ),
        "acres": "121.072",
        "interest": "Undivided 1/6 oil, gas, and coalbed methane",
        "consideration": "$11,137.50",
        "doc_url": "",
        "notes": (
            "VESTING INSTRUMENT. Master Mineral Holdings holds 1/6 interest. "
            "Remaining 5/6 undivided interest in Shuttleworth heirs — research required. "
            "1903 DB 136/259 reserved 1/2 minerals — Antero WV analysis applies."
        ),
    },
]

# Full result dict — compatible with CHAIN agent output schema
CHAIN_RESULT = {
    "agent":      "CHAIN",
    "status":     "COMPLETE",
    "source":     "manual",
    "count":      len(INSTRUMENTS),
    "instruments": INSTRUMENTS,
    "gaps": [
        "Gap: Monroe deeds (DB 57, 61, 68, 75) — title path Monroe → Shuttleworth not yet documented",
        "Gap: Stewart → Burns/Kramer — intermediate conveyances not yet retrieved",
        "Gap: Shuttleworth heirs (Fid 10/247) → present — 5/6 mineral interest chain incomplete",
    ],
    "errors": [],
    "legal_desc": "",
    "title_notes": [
        "WS title — Master Mineral Holdings Inc. holds undivided 1/6 O&G per BK 1441/1269",
        "1/2 mineral reservation: DB 136 P 259 (Shuttleworth to Stewart, 1903) — SPLIT ESTATE",
        "Antero WV mineral reservation analysis applies",
        "Remaining 5/6 undivided O&G interest: Shuttleworth heirs — further research required",
        "Surface owner: Burns family, Knoll View Road, Mount Clare WV 26408",
        "Tax: Shuttleworth Maynard Heirs .50 INT 121.072 AC O&G Gnatty Creek, Elk-Outside",
        "Parcels on record: 17-11-0409-0019-0000, -0001, -0002, -0003",
    ],
    "key_instruments": {
        "vesting":          "BK 1441 / PG 1269",
        "mineral_res":      "DB 136 / P 259 (1903)",
        "earliest":         "DB 57 / P 238 (1874)",
        "fiduciary":        "Fid Book 10 / P 247 (1919)",
    },
    "interest_held":    "Undivided 1/6 oil, gas, and coalbed methane",
    "grantee_current":  "Master Mineral Holdings Inc. (Texas corporation)",
    "consideration":    "$11,137.50",
    "deed_date":        "January 19, 2010",
    "recorded_date":    "February 10, 2010",
    "district":         "Elk-Outside",
    "county":           "Harrison",
    "state":            "WV",
    "parcels": [
        "17-11-0409-0019-0000",
        "17-11-0409-0019-0001",
        "17-11-0409-0019-0002",
        "17-11-0409-0019-0003",
    ],
    "surface_owner":    "Burns family, Knoll View Road, Mount Clare WV 26408",
    "tax_assessment":   "Shuttleworth Maynard Heirs .50 INT 121.072 AC O&G Gnatty Creek Elk-Outside",
    "acreage":          "121.072",
}
