"""
Manual chain-of-title seed for parcel 11-409-19 — Harrison County WV.
Source: Harrison County IDX + manual research.  All 16 instruments ordered oldest → newest.
"""

INSTRUMENTS = [
    {
        "seq": 1, "type": "DEED",
        "book": "57",   "page": "238",  "date_instr": "1874",
        "grantor": "DAVISSON, EDGAR M.",        "grantee": "MONROE, BENJAMIN T.",
        "acres": "51", "consideration": "",
        "description": "51 acres Gnatty Creek",
        "notes": "",
    },
    {
        "seq": 2, "type": "DEED",
        "book": "61",   "page": "434",  "date_instr": "1879",
        "grantor": "SHUTTLEWORTH, S.A.",        "grantee": "MONROE, B.T.",
        "acres": "", "consideration": "",
        "description": "Romines Mills tract",
        "notes": "",
    },
    {
        "seq": 3, "type": "DEED",
        "book": "68",   "page": "329",  "date_instr": "1884",
        "grantor": "BUMGARDNER, ADAM",          "grantee": "MONROE, B.T.",
        "acres": "60", "consideration": "",
        "description": "60 acres",
        "notes": "",
    },
    {
        "seq": 4, "type": "DEED",
        "book": "75",   "page": "97",   "date_instr": "1888",
        "grantor": "BUMGARDNER, ADAM",          "grantee": "MONROE, B.T.",
        "acres": "10", "consideration": "",
        "description": "10 acres",
        "notes": "",
    },
    {
        "seq": 5, "type": "DEED",
        "book": "109",  "page": "403",  "date_instr": "1899",
        "grantor": "THOMPSON, M.M., COMMISSIONER", "grantee": "SHUTTLEWORTH, M.N.",
        "acres": "122", "consideration": "",
        "description": "Circuit Court order",
        "notes": "",
    },
    {
        "seq": 6, "type": "DEED",
        "book": "136",  "page": "259",  "date_instr": "1903-03-23",
        "grantor": "SHUTTLEWORTH, MAYNARD N. & LILLIE", "grantee": "STEWART, WILLIAM A.",
        "acres": "121.5", "consideration": "",
        "description": "121.5 ac Elk Creek — RESERVED ONE-HALF OF ALL OIL AND GAS",
        "notes": "KEY split estate instrument — 1/2 mineral reservation to Shuttleworth heirs",
    },
    {
        "seq": 7, "type": "COAL DEED",
        "book": "136",  "page": "88",   "date_instr": "1903-02-09",
        "grantor": "PROPS, M.A. & WIFE",        "grantee": "BIJOU COAL COMPANY",
        "acres": "", "consideration": "",
        "description": "Pittsburgh seam of coal — UNRELEASED",
        "notes": "Encumbrance — no release of record",
    },
    {
        "seq": 8, "type": "OGL",
        "book": "183",  "page": "260",  "date_instr": "1909-05-04",
        "grantor": "PROPS, M.A. & WIFE",        "grantee": "HOPE NATURAL GAS COMPANY",
        "acres": "", "consideration": "",
        "description": "Oil and gas lease — UNRELEASED",
        "notes": "Pre-digital encumbrance — no release found",
    },
    {
        "seq": 9, "type": "ESTATE",
        "book": "10",   "page": "247",  "date_instr": "1919",
        "grantor": "SHUTTLEWORTH, M.N. — DIED",
        "grantee": "6 HEIRS (LILLIE, HELEN, LORENE, MARY, SAMUEL, BETTY JANE)",
        "acres": "", "consideration": "",
        "description": "Fiduciary — reserved mineral interest to heirs",
        "notes": "Helen Shuttleworth = Helen S. Kramer (per DB 1441/1269). "
                 "5 remaining heir shares not yet conveyed — research required.",
    },
    {
        "seq": 10, "type": "WILL/PROBATE",
        "book": "54",   "page": "291",  "date_instr": "1960",
        "grantor": "LAWSON, T. MINTER — DIED",  "grantee": "LAWSON, GUY & MARY",
        "acres": "", "consideration": "",
        "description": "Surface chain — Will Book",
        "notes": "",
    },
    {
        "seq": 11, "type": "WILL/PROBATE",
        "book": "79",   "page": "320",  "date_instr": "1971",
        "grantor": "LAWSON, GUY — DIED",        "grantee": "LAWSON, MARY",
        "acres": "", "consideration": "",
        "description": "Surface chain — Will Book",
        "notes": "",
    },
    {
        "seq": 12, "type": "WILL/PROBATE",
        "book": "102",  "page": "1040", "date_instr": "1983",
        "grantor": "LAWSON, MARY — DIED",       "grantee": "STOUT, ABNER — EXECUTOR",
        "acres": "", "consideration": "",
        "description": "Surface chain — Will Book",
        "notes": "",
    },
    {
        "seq": 13, "type": "WILL/PROBATE",
        "book": "108",  "page": "137",  "date_instr": "1980",
        "grantor": "SHUTTLEWORTH, LORENE — DIED",
        "grantee": "KRAMER, HELEN; EVANS, BETTY; SAMUEL SHUTTLEWORTH",
        "acres": "", "consideration": "",
        "description": "Lorene's mineral share distributed",
        "notes": "",
    },
    {
        "seq": 14, "type": "WILL/PROBATE",
        "book": "142",  "page": "359",  "date_instr": "1993",
        "grantor": "KRAMER, HELEN S. — DIED",   "grantee": "BURNS, A. DEAN — EXECUTOR",
        "acres": "", "consideration": "",
        "description": "Burns named Executor — leads to DB 1441/1269",
        "notes": "",
    },
    {
        "seq": 15, "type": "DEED",
        "book": "1197", "page": "1258", "date_instr": "1989-07-11",
        "date_rec": "1989-09-21",
        "grantor": "STOUT, ABNER, EXECUTOR (LAWSON ESTATE)",
        "grantee": "BURNS, L. CRAIG & SUE B.",
        "acres": "129.63", "consideration": "$34,500.00",
        "description": "SURFACE VESTING — exceptions: DB 136/88, DB 183/260",
        "notes": "Surface vesting instrument. Mineral rights excluded.",
    },
    {
        "seq": 16, "type": "MINERAL DEED",
        "book": "1441", "page": "1269", "date_instr": "2010-01-19",
        "date_rec": "2010-02-10",
        "grantor": "BURNS, A. DEAN, EXECUTOR (HELEN S. KRAMER ESTATE)",
        "grantee": "MASTER MINERAL HOLDINGS INC.",
        "acres": "121.072", "consideration": "$10.00",
        "description": "MINERAL VESTING — 1/6 undivided O&G + CBM",
        "notes": "VESTING INSTRUMENT. Parcels 17-11-0409-0019-0000 through -0003. "
                 "Tax: Shuttleworth Maynard Heirs .50 INT 121.072 AC O&G Gnatty Creek. "
                 "Entity discrepancy: deed=Master Mineral Holdings Inc. / "
                 "tax=Master Mineral Holdings III LP — same PO Box 10886 Midland TX 79702.",
    },
]
