"""
Manual chain-of-title seed for parcel 11-409-19.
Source: Harrison County IDX — BK 1441/1269 + manual research.
Instruments ordered oldest → newest.
"""

INSTRUMENTS = [
    {
        "seq": 1,
        "type": "DEED",
        "grantor": "DAVISSON, EDGAR M.",
        "grantee": "MONROE, BENJAMIN T.",
        "book": "57",
        "page": "238",
        "date_recorded": "1874",
        "date_instr": "1874",
        "description": "51 acres near Gnatty Creek",
        "acres": "51",
        "interest": "",
        "consideration": "",
        "doc_url": "",
        "notes": "",
    },
    {
        "seq": 2,
        "type": "DEED",
        "grantor": "SHUTTLEWORTH, S.A.",
        "grantee": "MONROE, B.T.",
        "book": "61",
        "page": "434",
        "date_recorded": "1879",
        "date_instr": "1879",
        "description": "Romines Mills tract",
        "acres": "",
        "interest": "",
        "consideration": "",
        "doc_url": "",
        "notes": "",
    },
    {
        "seq": 3,
        "type": "DEED",
        "grantor": "BUMGARDNER, ADAM",
        "grantee": "MONROE, B.T.",
        "book": "68",
        "page": "329",
        "date_recorded": "1884",
        "date_instr": "1884",
        "description": "60 acres fraction",
        "acres": "60",
        "interest": "",
        "consideration": "",
        "doc_url": "",
        "notes": "",
    },
    {
        "seq": 4,
        "type": "DEED",
        "grantor": "BUMGARDNER, ADAM",
        "grantee": "MONROE, B.T.",
        "book": "75",
        "page": "97",
        "date_recorded": "1888",
        "date_instr": "1888",
        "description": "10 acres fraction",
        "acres": "10",
        "interest": "",
        "consideration": "",
        "doc_url": "",
        "notes": "",
    },
    {
        "seq": 5,
        "type": "DEED",
        "grantor": "THOMPSON, M.M., COMMISSIONER",
        "grantee": "SHUTTLEWORTH, M.N.",
        "book": "109",
        "page": "403",
        "date_recorded": "1899",
        "date_instr": "1899",
        "description": "Circuit Court order",
        "acres": "",
        "interest": "",
        "consideration": "",
        "doc_url": "",
        "notes": "",
    },
    {
        "seq": 6,
        "type": "DEED",
        "grantor": "SHUTTLEWORTH, MAYNARD N. & LILLIE",
        "grantee": "STEWART, WILLIAM A.",
        "book": "136",
        "page": "259",
        "date_recorded": "1903",
        "date_instr": "1903",
        "description": "121.5 acres Elk Creek — RESERVED 1/2 MINERALS",
        "acres": "121.5",
        "interest": "Surface + 1/2 minerals conveyed; 1/2 minerals RESERVED by grantor",
        "consideration": "",
        "doc_url": "",
        "notes": "KEY: 1/2 mineral reservation creates split estate. Antero WV analysis applies.",
    },
    {
        "seq": 7,
        "type": "ESTATE / FIDUCIARY",
        "grantor": "SHUTTLEWORTH, MAYNARD N. — DIED",
        "grantee": "HEIRS: LILLIE A., HELEN, LORENE, MARY, SAMUEL, BETTY JANE SHUTTLEWORTH",
        "book": "FID 10",
        "page": "247",
        "date_recorded": "1919",
        "date_instr": "1919",
        "description": "Estate settlement — reserved mineral interest distributed to heirs",
        "acres": "",
        "interest": "Reserved 1/2 mineral interest distributed among 6 heirs",
        "consideration": "",
        "doc_url": "",
        "notes": "Helen Shuttleworth = Helen S. Kramer (confirmed in BK 1441/1269). "
                 "5 remaining heirs shares outstanding — research required.",
    },
    {
        "seq": 8,
        "type": "MINERAL DEED",
        "grantor": "BURNS, A. DEAN, EXECUTOR ESTATE OF HELEN S. KRAMER",
        "grantee": "MASTER MINERAL HOLDINGS INC., TEXAS CORPORATION",
        "book": "1441",
        "page": "1269",
        "date_recorded": "2010-02-10",
        "date_instr": "2010-01-19",
        "description": "1/6 undivided O&G interest — Elk-Outside District, Harrison County WV",
        "acres": "121.072",
        "interest": "Undivided 1/6 oil, gas, and coalbed methane",
        "consideration": "$11,137.50",
        "doc_url": "",
        "notes": "VESTING INSTRUMENT. Parcels 17-11-0409-0019-0000 through -0003. "
                 "Tax: Shuttleworth Maynard Heirs .50 INT 121.072 AC O&G Gnatty Creek. "
                 "Surface: Burns family, Knoll View Road, Mount Clare WV 26408.",
    },
]

CHAIN_RESULT = {
    "agent":      "CHAIN",
    "status":     "COMPLETE",
    "source":     "manual",
    "count":      len(INSTRUMENTS),
    "instruments": INSTRUMENTS,
    "gaps": [
        "Monroe deeds (DB 57/238, 61/434, 68/329, 75/97) — Monroe→Shuttleworth path not yet documented",
        "Stewart→Kramer/Burns — intermediate conveyances not yet retrieved",
        "Shuttleworth heirs (Fid 10/247) — 5/6 undivided mineral interest chain incomplete",
    ],
    "errors": [],
    "legal_desc": "",
    "title_notes": [
        "Master Mineral Holdings Inc. holds undivided 1/6 O&G per BK 1441/1269",
        "DB 136/259 (1903): Shuttleworth reserved 1/2 minerals — SPLIT ESTATE",
        "Antero WV mineral reservation analysis required",
        "5/6 undivided O&G — Shuttleworth heirs — further research required",
        "Surface owner: Burns family, Knoll View Road, Mount Clare WV 26408",
        "Tax: Shuttleworth Maynard Heirs .50 INT 121.072 AC O&G Gnatty Creek, Elk-Outside",
        "Parcels: 17-11-0409-0019-0000, -0001, -0002, -0003",
    ],
    "key_instruments": {
        "vesting":     "BK 1441 / PG 1269",
        "mineral_res": "DB 136 / P 259 (1903)",
        "earliest":    "DB 57 / P 238 (1874)",
        "fiduciary":   "Fid Book 10 / P 247 (1919)",
    },
    "interest_held":   "Undivided 1/6 oil, gas, and coalbed methane",
    "grantee_current": "Master Mineral Holdings Inc. (Texas corporation)",
    "consideration":   "$11,137.50",
    "deed_date":       "January 19, 2010",
    "recorded_date":   "February 10, 2010",
    "district":        "Elk-Outside",
    "county":          "Harrison",
    "state":           "WV",
    "parcels": [
        "17-11-0409-0019-0000",
        "17-11-0409-0019-0001",
        "17-11-0409-0019-0002",
        "17-11-0409-0019-0003",
    ],
    "surface_owner":  "Burns family, Knoll View Road, Mount Clare WV 26408",
    "tax_assessment": "Shuttleworth Maynard Heirs .50 INT 121.072 AC O&G Gnatty Creek Elk-Outside",
    "acreage":        "121.072",
}
