// WV County Knowledge — Texhoma Namespace Only
// Installed for Contract 52446 — Elk Prospect

export type WVCounty = {
  name: string;
  countySeat: string;
  clerkPhone: string;
  portalUrl: string | null;
  portalType: 'online' | 'partial' | 'paper';
  ogActivityLevel: 'highest' | 'very_high' | 'high' | 'moderate' | 'low';
  tier: 1 | 2 | 3 | 4;
  activeOperators: string[];
  formations: string[];
  knownIssues: string[];
  notes: string;
  elkProbability: boolean;
};

export const WV_COUNTIES: WVCounty[] = [
  {
    name: 'Doddridge',
    countySeat: 'West Union',
    clerkPhone: '(304) 873-2631',
    portalUrl: null,
    portalType: 'online',
    ogActivityLevel: 'highest',
    tier: 1,
    activeOperators: ['EQT', 'Antero Resources', 'CNX Resources'],
    formations: ['Marcellus', 'Utica', 'Upper Devonian'],
    knownIssues: [
      'Heavy horizontal unit complexity',
      'Frequent depth severances',
      'Old family mineral splits',
    ],
    notes: 'Most active Marcellus county in WV. Core EQT territory.',
    elkProbability: false,
  },
  {
    name: 'Wetzel',
    countySeat: 'New Martinsville',
    clerkPhone: '(304) 455-8220',
    portalUrl: null,
    portalType: 'partial',
    ogActivityLevel: 'very_high',
    tier: 1,
    activeOperators: ['EQT', 'Antero Resources'],
    formations: ['Marcellus', 'Utica'],
    knownIssues: [
      'Old flat rate leases common',
      'Royalty conversion issues post-2018',
    ],
    notes: 'EQT dominant. Critical county for EQT Appalachia work.',
    elkProbability: false,
  },
  {
    name: 'Tyler',
    countySeat: 'Middlebourne',
    clerkPhone: '(304) 758-2102',
    portalUrl: null,
    portalType: 'partial',
    ogActivityLevel: 'high',
    tier: 1,
    activeOperators: ['EQT', 'Antero Resources'],
    formations: ['Marcellus', 'Utica'],
    knownIssues: ['Old family mineral splits from early 1900s'],
    notes: 'Active O&G. Manageable county size.',
    elkProbability: false,
  },
  {
    name: 'Pleasants',
    countySeat: 'St. Marys',
    clerkPhone: '(304) 684-3542',
    portalUrl: null,
    portalType: 'partial',
    ogActivityLevel: 'high',
    tier: 1,
    activeOperators: ['EQT', 'Antero Resources'],
    formations: ['Marcellus'],
    knownIssues: [],
    notes: 'Smaller county, manageable record volume.',
    elkProbability: false,
  },
  {
    name: 'Wood',
    countySeat: 'Parkersburg',
    clerkPhone: '(304) 424-1850',
    portalUrl: 'https://www.woodcountywv.com/county-clerk',
    portalType: 'online',
    ogActivityLevel: 'high',
    tier: 1,
    activeOperators: ['EQT', 'Antero Resources', 'CNX Resources'],
    formations: ['Marcellus', 'Utica', 'Upper Devonian'],
    knownIssues: [],
    notes: 'Major hub. Parkersburg is WV O&G center. Strong online records.',
    elkProbability: false,
  },
  {
    name: 'Wirt',
    countySeat: 'Elizabeth',
    clerkPhone: '(304) 275-4271',
    portalUrl: null,
    portalType: 'paper',
    ogActivityLevel: 'high',
    tier: 1,
    activeOperators: ['Antero Resources'],
    formations: ['Marcellus'],
    knownIssues: ['Mostly paper records — courthouse visit likely required'],
    notes: 'Small county. Plan physical visit for older records.',
    elkProbability: false,
  },
  {
    name: 'Roane',
    countySeat: 'Spencer',
    clerkPhone: '(304) 927-2860',
    portalUrl: null,
    portalType: 'partial',
    ogActivityLevel: 'high',
    tier: 1,
    activeOperators: ['Various independents'],
    formations: ['Marcellus', 'Shallow gas'],
    knownIssues: ['Older record system'],
    notes: 'Active O&G with older infrastructure.',
    elkProbability: false,
  },
  {
    name: 'Calhoun',
    countySeat: 'Grantsville',
    clerkPhone: '(304) 354-6725',
    portalUrl: null,
    portalType: 'paper',
    ogActivityLevel: 'high',
    tier: 1,
    activeOperators: ['Various independents'],
    formations: ['Shallow gas', 'Marcellus'],
    knownIssues: ['Very small county', 'Mostly paper records'],
    notes: 'Plan physical courthouse visit.',
    elkProbability: false,
  },
  {
    name: 'Jackson',
    countySeat: 'Ripley',
    clerkPhone: '(304) 373-2230',
    portalUrl: null,
    portalType: 'partial',
    ogActivityLevel: 'high',
    tier: 1,
    activeOperators: ['EQT', 'Various'],
    formations: ['Marcellus'],
    knownIssues: [],
    notes: 'Growing Marcellus activity.',
    elkProbability: false,
  },
  // ELK RIVER CORRIDOR — TIER 2
  {
    name: 'Nicholas',
    countySeat: 'Summersville',
    clerkPhone: '(304) 872-7820',
    portalUrl: null,
    portalType: 'partial',
    ogActivityLevel: 'high',
    tier: 2,
    activeOperators: ['Various'],
    formations: ['Marcellus', 'Shallow gas'],
    knownIssues: ['Heirship issues common in older chains'],
    notes: 'PRIORITY — Elk River runs through this county. High probability for Elk prospect.',
    elkProbability: true,
  },
  {
    name: 'Clay',
    countySeat: 'Clay',
    clerkPhone: '(304) 587-4259',
    portalUrl: null,
    portalType: 'paper',
    ogActivityLevel: 'moderate',
    tier: 2,
    activeOperators: ['Various independents'],
    formations: ['Shallow gas', 'Marcellus'],
    knownIssues: ['Older records', 'Heirship issues very common'],
    notes: 'Elk River corridor. Smaller county. Paper records likely.',
    elkProbability: true,
  },
  {
    name: 'Kanawha',
    countySeat: 'Charleston',
    clerkPhone: '(304) 357-0130',
    portalUrl: 'https://www.kanawha.us/county-clerk',
    portalType: 'online',
    ogActivityLevel: 'high',
    tier: 2,
    activeOperators: ['Multiple majors and independents'],
    formations: ['Marcellus', 'Utica', 'Shallow gas'],
    knownIssues: [],
    notes: 'State capital. Best records infrastructure in WV. Strong online access. Elk River runs through.',
    elkProbability: true,
  },
  {
    name: 'Braxton',
    countySeat: 'Sutton',
    clerkPhone: '(304) 765-2833',
    portalUrl: null,
    portalType: 'partial',
    ogActivityLevel: 'moderate',
    tier: 2,
    activeOperators: ['Various independents'],
    formations: ['Shallow gas', 'Marcellus'],
    knownIssues: [],
    notes: 'Elk River headwaters area.',
    elkProbability: true,
  },
  {
    name: 'Webster',
    countySeat: 'Webster Springs',
    clerkPhone: '(304) 847-2508',
    portalUrl: null,
    portalType: 'paper',
    ogActivityLevel: 'moderate',
    tier: 2,
    activeOperators: ['Various independents'],
    formations: ['Shallow gas'],
    knownIssues: ['Remote county', 'Physical visit required for most records'],
    notes: 'Upper Elk River. Courthouse visit required.',
    elkProbability: true,
  },
  {
    name: 'Upshur',
    countySeat: 'Buckhannon',
    clerkPhone: '(304) 472-1068',
    portalUrl: null,
    portalType: 'partial',
    ogActivityLevel: 'high',
    tier: 2,
    activeOperators: ['EQT', 'Various'],
    formations: ['Marcellus', 'Utica'],
    knownIssues: [],
    notes: 'Active area with good records.',
    elkProbability: true,
  },
  // MARCELLUS CORRIDOR — TIER 3
  {
    name: 'Marshall',
    countySeat: 'Moundsville',
    clerkPhone: '(304) 845-1220',
    portalUrl: null,
    portalType: 'partial',
    ogActivityLevel: 'high',
    tier: 3,
    activeOperators: ['EQT', 'CNX Resources'],
    formations: ['Marcellus', 'Utica'],
    knownIssues: [],
    notes: 'Northern panhandle. Active Marcellus.',
    elkProbability: false,
  },
  {
    name: 'Marion',
    countySeat: 'Fairmont',
    clerkPhone: '(304) 367-5440',
    portalUrl: null,
    portalType: 'partial',
    ogActivityLevel: 'high',
    tier: 3,
    activeOperators: ['EQT', 'CNX Resources'],
    formations: ['Marcellus', 'Utica'],
    knownIssues: [],
    notes: 'Fairmont is a major O&G hub in WV.',
    elkProbability: false,
  },
  {
    name: 'Monongalia',
    countySeat: 'Morgantown',
    clerkPhone: '(304) 291-7230',
    portalUrl: 'https://www.monongaliacounty.org/county-clerk',
    portalType: 'online',
    ogActivityLevel: 'high',
    tier: 3,
    activeOperators: ['EQT', 'CNX Resources', 'Southwestern Energy'],
    formations: ['Marcellus', 'Utica'],
    knownIssues: [],
    notes: 'WVU area. Strong records. Active Marcellus.',
    elkProbability: false,
  },
  {
    name: 'Harrison',
    countySeat: 'Clarksburg',
    clerkPhone: '(304) 624-8650',
    portalUrl: null,
    portalType: 'online',
    ogActivityLevel: 'high',
    tier: 3,
    activeOperators: ['EQT', 'CNX Resources'],
    formations: ['Marcellus', 'Utica'],
    knownIssues: [],
    notes: 'Major Marcellus county. Online access available.',
    elkProbability: false,
  },
  {
    name: 'Lewis',
    countySeat: 'Weston',
    clerkPhone: '(304) 269-8210',
    portalUrl: null,
    portalType: 'partial',
    ogActivityLevel: 'high',
    tier: 3,
    activeOperators: ['EQT', 'Various'],
    formations: ['Marcellus'],
    knownIssues: [],
    notes: 'Active Marcellus area.',
    elkProbability: false,
  },
  {
    name: 'Barbour',
    countySeat: 'Philippi',
    clerkPhone: '(304) 457-2232',
    portalUrl: null,
    portalType: 'partial',
    ogActivityLevel: 'high',
    tier: 3,
    activeOperators: ['Various'],
    formations: ['Marcellus'],
    knownIssues: [],
    notes: '',
    elkProbability: false,
  },
  {
    name: 'Taylor',
    countySeat: 'Grafton',
    clerkPhone: '(304) 265-1401',
    portalUrl: null,
    portalType: 'partial',
    ogActivityLevel: 'moderate',
    tier: 3,
    activeOperators: ['Various'],
    formations: ['Marcellus'],
    knownIssues: [],
    notes: '',
    elkProbability: false,
  },
  {
    name: 'Tucker',
    countySeat: 'Parsons',
    clerkPhone: '(304) 478-2871',
    portalUrl: null,
    portalType: 'partial',
    ogActivityLevel: 'moderate',
    tier: 3,
    activeOperators: ['Various'],
    formations: ['Marcellus'],
    knownIssues: [],
    notes: '',
    elkProbability: false,
  },
  {
    name: 'Preston',
    countySeat: 'Kingwood',
    clerkPhone: '(304) 329-0070',
    portalUrl: null,
    portalType: 'partial',
    ogActivityLevel: 'moderate',
    tier: 3,
    activeOperators: ['Various'],
    formations: ['Marcellus'],
    knownIssues: [],
    notes: '',
    elkProbability: false,
  },
  {
    name: 'Randolph',
    countySeat: 'Elkins',
    clerkPhone: '(304) 636-0543',
    portalUrl: null,
    portalType: 'partial',
    ogActivityLevel: 'moderate',
    tier: 3,
    activeOperators: ['Various'],
    formations: ['Marcellus'],
    knownIssues: [],
    notes: '',
    elkProbability: false,
  },
  {
    name: 'Ritchie',
    countySeat: 'Harrisville',
    clerkPhone: '(304) 643-2164',
    portalUrl: null,
    portalType: 'partial',
    ogActivityLevel: 'high',
    tier: 3,
    activeOperators: ['Antero Resources', 'Various'],
    formations: ['Marcellus', 'Shallow gas'],
    knownIssues: [],
    notes: 'More active than tier suggests.',
    elkProbability: false,
  },
  // TIER 4 — REMAINING COUNTIES
  {
    name: 'Berkeley', countySeat: 'Martinsburg',
    clerkPhone: '(304) 264-1921', portalUrl: null,
    portalType: 'partial', ogActivityLevel: 'low', tier: 4,
    activeOperators: [], formations: [], knownIssues: [], notes: '',
    elkProbability: false,
  },
  {
    name: 'Boone', countySeat: 'Madison',
    clerkPhone: '(304) 369-7330', portalUrl: null,
    portalType: 'partial', ogActivityLevel: 'moderate', tier: 4,
    activeOperators: ['Various coal/gas'], formations: ['Shallow gas', 'Coal'],
    knownIssues: ['Coal/gas rights often split'], notes: 'Southern WV coal country.',
    elkProbability: false,
  },
  {
    name: 'Brooke', countySeat: 'Wellsburg',
    clerkPhone: '(304) 737-3661', portalUrl: null,
    portalType: 'partial', ogActivityLevel: 'moderate', tier: 4,
    activeOperators: ['EQT'], formations: ['Marcellus'],
    knownIssues: [], notes: 'Northern panhandle tip.',
    elkProbability: false,
  },
  {
    name: 'Cabell', countySeat: 'Huntington',
    clerkPhone: '(304) 526-8625', portalUrl: null,
    portalType: 'partial', ogActivityLevel: 'low', tier: 4,
    activeOperators: [], formations: [], knownIssues: [], notes: '',
    elkProbability: false,
  },
  {
    name: 'Fayette', countySeat: 'Fayetteville',
    clerkPhone: '(304) 574-4234', portalUrl: null,
    portalType: 'partial', ogActivityLevel: 'moderate', tier: 4,
    activeOperators: ['Various'], formations: ['Shallow gas'],
    knownIssues: [], notes: '',
    elkProbability: false,
  },
  {
    name: 'Gilmer', countySeat: 'Glenville',
    clerkPhone: '(304) 462-7641', portalUrl: null,
    portalType: 'paper', ogActivityLevel: 'moderate', tier: 4,
    activeOperators: ['Various independents'], formations: ['Shallow gas', 'Marcellus'],
    knownIssues: ['Paper records'], notes: '',
    elkProbability: false,
  },
  {
    name: 'Grant', countySeat: 'Petersburg',
    clerkPhone: '(304) 257-4550', portalUrl: null,
    portalType: 'paper', ogActivityLevel: 'low', tier: 4,
    activeOperators: [], formations: [], knownIssues: [], notes: '',
    elkProbability: false,
  },
  {
    name: 'Greenbrier', countySeat: 'Lewisburg',
    clerkPhone: '(304) 647-6602', portalUrl: null,
    portalType: 'partial', ogActivityLevel: 'low', tier: 4,
    activeOperators: [], formations: [], knownIssues: [], notes: '',
    elkProbability: false,
  },
  {
    name: 'Hampshire', countySeat: 'Romney',
    clerkPhone: '(304) 822-5112', portalUrl: null,
    portalType: 'paper', ogActivityLevel: 'low', tier: 4,
    activeOperators: [], formations: [], knownIssues: [], notes: '',
    elkProbability: false,
  },
  {
    name: 'Hancock', countySeat: 'New Cumberland',
    clerkPhone: '(304) 564-3311', portalUrl: null,
    portalType: 'partial', ogActivityLevel: 'moderate', tier: 4,
    activeOperators: ['EQT'], formations: ['Marcellus'],
    knownIssues: [], notes: 'Northern tip of panhandle.',
    elkProbability: false,
  },
  {
    name: 'Hardy', countySeat: 'Moorefield',
    clerkPhone: '(304) 530-0220', portalUrl: null,
    portalType: 'paper', ogActivityLevel: 'low', tier: 4,
    activeOperators: [], formations: [], knownIssues: [], notes: '',
    elkProbability: false,
  },
  {
    name: 'Jefferson', countySeat: 'Charles Town',
    clerkPhone: '(304) 728-3215', portalUrl: null,
    portalType: 'partial', ogActivityLevel: 'low', tier: 4,
    activeOperators: [], formations: [], knownIssues: [], notes: '',
    elkProbability: false,
  },
  {
    name: 'Lincoln', countySeat: 'Hamlin',
    clerkPhone: '(304) 824-3336', portalUrl: null,
    portalType: 'partial', ogActivityLevel: 'moderate', tier: 4,
    activeOperators: ['Various'], formations: ['Shallow gas'],
    knownIssues: [], notes: '',
    elkProbability: false,
  },
  {
    name: 'Logan', countySeat: 'Logan',
    clerkPhone: '(304) 792-8540', portalUrl: null,
    portalType: 'partial', ogActivityLevel: 'moderate', tier: 4,
    activeOperators: ['Various coal/gas'], formations: ['Shallow gas', 'Coal'],
    knownIssues: ['Coal/gas rights often split'], notes: 'Southern WV.',
    elkProbability: false,
  },
  {
    name: 'Mason', countySeat: 'Point Pleasant',
    clerkPhone: '(304) 675-1997', portalUrl: null,
    portalType: 'partial', ogActivityLevel: 'moderate', tier: 4,
    activeOperators: ['Various'], formations: ['Marcellus'],
    knownIssues: [], notes: '',
    elkProbability: false,
  },
  {
    name: 'McDowell', countySeat: 'Welch',
    clerkPhone: '(304) 436-8544', portalUrl: null,
    portalType: 'partial', ogActivityLevel: 'moderate', tier: 4,
    activeOperators: ['Various coal/gas'], formations: ['Coal', 'Shallow gas'],
    knownIssues: ['Coal/gas rights often split'], notes: 'Deep southern WV.',
    elkProbability: false,
  },
  {
    name: 'Mercer', countySeat: 'Princeton',
    clerkPhone: '(304) 487-8311', portalUrl: null,
    portalType: 'partial', ogActivityLevel: 'low', tier: 4,
    activeOperators: [], formations: [], knownIssues: [], notes: '',
    elkProbability: false,
  },
  {
    name: 'Mineral', countySeat: 'Keyser',
    clerkPhone: '(304) 788-3462', portalUrl: null,
    portalType: 'paper', ogActivityLevel: 'low', tier: 4,
    activeOperators: [], formations: [], knownIssues: [], notes: '',
    elkProbability: false,
  },
  {
    name: 'Mingo', countySeat: 'Williamson',
    clerkPhone: '(304) 235-0330', portalUrl: null,
    portalType: 'partial', ogActivityLevel: 'moderate', tier: 4,
    activeOperators: ['Various'], formations: ['Shallow gas'],
    knownIssues: [], notes: 'Southern WV near KY border.',
    elkProbability: false,
  },
  {
    name: 'Monroe', countySeat: 'Union',
    clerkPhone: '(304) 772-3096', portalUrl: null,
    portalType: 'paper', ogActivityLevel: 'low', tier: 4,
    activeOperators: [], formations: [], knownIssues: [], notes: '',
    elkProbability: false,
  },
  {
    name: 'Morgan', countySeat: 'Berkeley Springs',
    clerkPhone: '(304) 258-8547', portalUrl: null,
    portalType: 'paper', ogActivityLevel: 'low', tier: 4,
    activeOperators: [], formations: [], knownIssues: [], notes: '',
    elkProbability: false,
  },
  {
    name: 'Ohio', countySeat: 'Wheeling',
    clerkPhone: '(304) 234-3628', portalUrl: null,
    portalType: 'partial', ogActivityLevel: 'moderate', tier: 4,
    activeOperators: ['EQT', 'Various'], formations: ['Marcellus'],
    knownIssues: [], notes: 'Wheeling area. Northern panhandle.',
    elkProbability: false,
  },
  {
    name: 'Pendleton', countySeat: 'Franklin',
    clerkPhone: '(304) 358-2505', portalUrl: null,
    portalType: 'paper', ogActivityLevel: 'low', tier: 4,
    activeOperators: [], formations: [], knownIssues: [], notes: '',
    elkProbability: false,
  },
  {
    name: 'Pocahontas', countySeat: 'Marlinton',
    clerkPhone: '(304) 799-4549', portalUrl: null,
    portalType: 'paper', ogActivityLevel: 'low', tier: 4,
    activeOperators: [], formations: [], knownIssues: [], notes: '',
    elkProbability: false,
  },
  {
    name: 'Putnam', countySeat: 'Winfield',
    clerkPhone: '(304) 586-0202', portalUrl: null,
    portalType: 'partial', ogActivityLevel: 'moderate', tier: 4,
    activeOperators: ['Various'], formations: ['Shallow gas'],
    knownIssues: [], notes: '',
    elkProbability: false,
  },
  {
    name: 'Raleigh', countySeat: 'Beckley',
    clerkPhone: '(304) 255-9123', portalUrl: null,
    portalType: 'partial', ogActivityLevel: 'moderate', tier: 4,
    activeOperators: ['Various coal/gas'], formations: ['Coal', 'Shallow gas'],
    knownIssues: ['Coal/gas rights often split'], notes: '',
    elkProbability: false,
  },
  {
    name: 'Summers', countySeat: 'Hinton',
    clerkPhone: '(304) 466-7104', portalUrl: null,
    portalType: 'paper', ogActivityLevel: 'low', tier: 4,
    activeOperators: [], formations: [], knownIssues: [], notes: '',
    elkProbability: false,
  },
  {
    name: 'Wayne', countySeat: 'Wayne',
    clerkPhone: '(304) 272-6369', portalUrl: null,
    portalType: 'partial', ogActivityLevel: 'moderate', tier: 4,
    activeOperators: ['Various'], formations: ['Shallow gas'],
    knownIssues: [], notes: '',
    elkProbability: false,
  },
  {
    name: 'Wyoming', countySeat: 'Pineville',
    clerkPhone: '(304) 732-8000', portalUrl: null,
    portalType: 'partial', ogActivityLevel: 'moderate', tier: 4,
    activeOperators: ['Various coal/gas'], formations: ['Coal', 'Shallow gas'],
    knownIssues: ['Coal/gas rights often split'], notes: '',
    elkProbability: false,
  },
];

export const ELK_CORRIDOR_COUNTIES  = WV_COUNTIES.filter((c) => c.elkProbability);
export const TIER_1_COUNTIES        = WV_COUNTIES.filter((c) => c.tier === 1);
export const getCountyByName        = (name: string) =>
  WV_COUNTIES.find((c) => c.name.toLowerCase() === name.toLowerCase());
